# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(646, 588)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txt_sms_num = QtGui.QTextEdit(self.centralwidget)
        self.txt_sms_num.setMinimumSize(QtCore.QSize(200, 200))
        self.txt_sms_num.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txt_sms_num.setObjectName(_fromUtf8("txt_sms_num"))
        self.horizontalLayout_2.addWidget(self.txt_sms_num)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(320, -1, -1, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.btn_send = QtGui.QPushButton(self.centralwidget)
        self.btn_send.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_send.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_send.setObjectName(_fromUtf8("btn_send"))
        self.verticalLayout_5.addWidget(self.btn_send)
        self.btn_info = QtGui.QPushButton(self.centralwidget)
        self.btn_info.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_info.setObjectName(_fromUtf8("btn_info"))
        self.verticalLayout_5.addWidget(self.btn_info)
        self.btn_exit = QtGui.QPushButton(self.centralwidget)
        self.btn_exit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_exit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_exit.setObjectName(_fromUtf8("btn_exit"))
        self.verticalLayout_5.addWidget(self.btn_exit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.txt_sms_text = QtGui.QTextEdit(self.centralwidget)
        self.txt_sms_text.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_sms_text.setMaximumSize(QtCore.QSize(16777215, 150))
        self.txt_sms_text.setObjectName(_fromUtf8("txt_sms_text"))
        self.verticalLayout_3.addWidget(self.txt_sms_text)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.txt_log = QtGui.QTextEdit(self.centralwidget)
        self.txt_log.setMaximumSize(QtCore.QSize(16777215, 150))
        self.txt_log.setObjectName(_fromUtf8("txt_log"))
        self.verticalLayout_3.addWidget(self.txt_log)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menu_open = QtGui.QAction(MainWindow)
        self.menu_open.setObjectName(_fromUtf8("menu_open"))
        self.menu_save = QtGui.QAction(MainWindow)
        self.menu_save.setObjectName(_fromUtf8("menu_save"))
        self.menu_save_as = QtGui.QAction(MainWindow)
        self.menu_save_as.setObjectName(_fromUtf8("menu_save_as"))
        self.menu_create = QtGui.QAction(MainWindow)
        self.menu_create.setObjectName(_fromUtf8("menu_create"))
        self.menu_preferences = QtGui.QAction(MainWindow)
        self.menu_preferences.setObjectName(_fromUtf8("menu_preferences"))
        self.menu_exit = QtGui.QAction(MainWindow)
        self.menu_exit.setObjectName(_fromUtf8("menu_exit"))
        self.menu.addAction(self.menu_open)
        self.menu.addAction(self.menu_save)
        self.menu.addAction(self.menu_save_as)
        self.menu.addAction(self.menu_create)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_preferences)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SMS Sender", None))
        self.label_3.setText(_translate("MainWindow", "Номера телефонов", None))
        self.btn_send.setText(_translate("MainWindow", "Отправить", None))
        self.btn_info.setText(_translate("MainWindow", "Инфо", None))
        self.btn_exit.setText(_translate("MainWindow", "Выход", None))
        self.label_2.setText(_translate("MainWindow", "Тест сообщения", None))
        self.label.setText(_translate("MainWindow", "Лог работы", None))
        self.menu.setTitle(_translate("MainWindow", "Файл", None))
        self.menu_open.setText(_translate("MainWindow", "Открыть", None))
        self.menu_save.setText(_translate("MainWindow", "Сохранить", None))
        self.menu_save_as.setText(_translate("MainWindow", "Сохранить как", None))
        self.menu_create.setText(_translate("MainWindow", "Создать", None))
        self.menu_preferences.setText(_translate("MainWindow", "Настройки", None))
        self.menu_exit.setText(_translate("MainWindow", "Выход", None))

